#!/bin/sh

cp -fr 0.orig/* 0

blockMesh

impesFoam

if true
then
    foamToEnsight -noZero
    foamToVTK
fi

touch sim.foam

#------------------------------------------------------------------------------
